name: Build icon data

on:
  push:
    branches:
      - main
    paths:
      - "icons/*.svg"
      - "icons/*.json"
      - "scripts/build-icons-json.mjs"
      - ".github/workflows/build-icons-json.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-icons-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false

      - name: Build dist files
        run: node scripts/build-icons-json.mjs

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f dist/icons.json dist/icons.min.json dist/icons-meta.json dist/icons-search.json

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore: update generated icon data"
          git push origin HEAD:${{ github.ref_name }}
